### PR TITLE
add socal 2020

### PR DESCRIPTION
**Pull request by malcolmbarrett**

### CODE REVIEW

**Review by daroczig — APPROVED** [review]
maybe add a pointer to the homepage as well -- like in some other events?

**Comment by malcolmbarrett** [comment]
Yes, of course! Will that be [socal2020.satrdays.org]() if we use GH pages on our current repo?

**Comment by daroczig** [comment]
> Will that be socal2020.satrdays.org if we use GH pages on our current repo?

You need to commit a cname file and we need to add a cname record in cloudflare for that ... without making those 2 happen, I think it would be satRdays.github.io/satrdaysocal2020 -- but please double check in the GH docs

**Comment by malcolmbarrett** [comment]
cc @EmilHvitfeldt who will be handling the website. I will assume we will get the first URL and put that in

**Comment by malcolmbarrett** [comment]
Ok added

**Comment by daroczig** [comment]
looks good, thanks :+1: 

@amy17519 can you pls take a second look and merge when you have a chance?

**Comment by amy17519** [comment]
this is awesome @malcolmbarrett @daroczig @EmilHvitfeldt. Let me know if you need help

**Pull request merged**
