### PR TITLE
PR for calender for satRday event in Melbourne Australia

### PR DESCRIPTION
**Pull request by psychtek**
Slack channel created locally with interested stakeholders ready to get involved.

### CODE REVIEW

**Review by daroczig — APPROVED** [review]
can you pls update the  slots filled as well?

**Comment by amy17519** [comment]
@psychtek are you still interested in hosting next quarter?

**Comment by psychtek** [comment]
@amy17519 Apologies for the lengthy delayed response. Things got super busy this end. We are looking to reschedule possibly later in the year. Can we close this off and will resubmit a calender request once we have met this end to confirm event.

**Comment by amy17519** [comment]
no problem. Thanks for letting us know!

**Pull request closed without merging**
